Repository BAMresearch/bam-masterdata, pull requests merged in 2025-09, with the labels that each got.

#181 added space support
  bam_masterdata/cli/cli.py
Labels: feature

#191 Fix paths in docu
  docs/explanations/parsing_structure.md
  docs/howtos/parsing/parser_app.md
Labels: docs

#194 Fix serialization issue
  bam_masterdata/metadata/entities.py
Labels: fix

#195 Fix printing of classes
  bam_masterdata/metadata/entities.py
  tests/metadata/test_entities.py
Labels: UX, fix
